### ISSUE TITLE
Tomcat not able to get it running

### ISSUE THREAD

**Issue by vmeganathan81** [MeteoGroup/jbrotli#6] opened 2016-06-13 13:37 UTC
Hi,

just downloaded your project, trying to get it working with Tomcat both Windows and Linux

i followed theses steps

1. downloaded the brotli project from google and placed it in the folder brotli of your project
2. Downloaded the CMAKE, to compile or run the build.bat file, but was not able to do so.

Not able to move forward with this.

I am looking for something like jar file for the wrapper your have writter or dll file. 

Thanks,
Vijay

**Comment by nitram509** [comment] 2016-06-14 19:33
I've already compiled all required JAR files.
When you use Maven or Gradle for you Java project, you can easily use
https://bintray.com/nitram509/jbrotli/jbrotli/view

At this site, you can also download the JAR files (including DLLs) manually.

Does this fit you needs?

**Comment by vmeganathan81** [comment] 2016-06-15 18:34
I am getting the below error, I tried to create dll from google/brotli using CMAKE was not able to do so

SEVERE: Exception starting filter BrotliFilter
javax.servlet.ServletException: java.lang.UnsatisfiedLinkError: Couldn't load native library 'brotli'. [LoaderResult: os.name="Windows 8", os.arch="amd64", os.version="6.2", java.vm.name="Java HotSpot(TM) 64-Bit Server VM", java.vm.version="25.45-b02", java.vm.vendor="Oracle Corporation", alreadyLoaded="null", loadedFromSystemLibraryPath="false", nativeLibName="brotli.dll", temporaryLibFile="C:\Program Files\Apache Software Foundation\Tomcat 7.0_T7Brotli\temp\brotli5858609841706117769\brotli.dll", libNameWithinClasspath="/lib/win32-x86-amd64/brotli.dll", usedThisClassloader="false", usedSystemClassloader="false", java.library.path="C:\Program Files\Apache Software Foundation\Tomcat 7.0_T7Brotli\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\MySQL\MySQL Utilities 1.3.6\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1\;C:\Program Files (x86)\nodejs\;C:\eClinicalWorks\jdk16\bin;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Kodak\Document Imaging\kds_i900\Smart Touch\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\CMake 2.8;."]
	at org.meteogroup.jbrotli.servlet.BrotliServletFilter.init(BrotliServletFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4908)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5602)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by nitram509** [comment] 2016-06-15 23:54
Vijay,

now I understand, you're trying to use the Tomcat example right?

Do you have jbrotli-native-win32-x86-amd64-0.5.0.jar in your classpath?

**Comment by vmeganathan81** [comment] 2016-06-16 02:09
![capture](https://cloud.githubusercontent.com/assets/19844029/16103349/c9552ab0-3345-11e6-8652-b6f1023332a4.PNG)

Have attached the file

**Comment by vmeganathan81** [comment] 2016-06-16 02:38
New Error


SEVERE: Exception starting filter BrotliFilter
javax.servlet.ServletException: java.lang.UnsatisfiedLinkError: C:\Program Files\Apache Software Foundation\Tomcat 7.0_T7Brotli\temp\brotli9053215835360680489\brotli.dll: Can't find dependent libraries
	at org.meteogroup.jbrotli.servlet.BrotliServletFilter.init(BrotliServletFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4908)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5602)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: C:\Program Files\Apache Software Foundation\Tomcat 7.0_T7Brotli\temp\brotli9053215835360680489\brotli.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.Runtime.load(Unknown Source)
	at org.meteogroup.jbrotli.libloader.LibraryLoader.tryLoadingFromTemporaryFolder(LibraryLoader.java:79)
	at org.meteogroup.jbrotli.libloader.BrotliLibraryLoader.loadBrotli(BrotliLibraryLoader.java:33)
	at org.meteogroup.jbrotli.servlet.BrotliServletFilter.init(BrotliServletFilter.java:86)
	... 16 more

**Comment by vmeganathan81** [comment] 2016-06-16 02:47
![capture](https://cloud.githubusercontent.com/assets/19844029/16103961/0d7d7472-334b-11e6-81c5-24a83d15b667.PNG)

Here are the list of jar files have copied

**Comment by nitram509** [comment] 2016-06-16 08:08
Thank you for the screenshots. Great idea, now I understand.

When you have downloaded all the files, you don't need CMAKE anymore.
The DLL is already in the jbrotli-native-win32-x86-amd64-0.5.0.jar.
jBrotli will automatically use it.

But, I think the problem is something else. The error message 
"brotli.dll: Can't find dependent libraries" could also mean, that the DLL requires some Visual Studio
runtime DLL files.

Would you please install Microsoft's Visual C++ Redistributable for Visual Studio 2015
and check if it's working then? The official installer you find here:
https://www.microsoft.com/download/details.aspx?id=48145

**Comment by nitram509** [comment] 2016-06-16 08:25
One side note:
Regarding your screenshot the CLASSPATH setting ...

I recommend you, to NOT use the environment variable CLASSPATH at all.
This will lead to a lot of problems. Tomcat manages it's own CLASSPATH very well.
I propose to delete this environment variable completely, to ensure a stable system.

**Comment by vmeganathan81** [comment] 2016-06-16 19:27
Hi,

Can we have those jar files compile in jdk 6.

EVERE: Error deploying configuration descriptor mobiledoc.xml
java.lang.UnsupportedClassVersionError: org/meteogroup/jbrotli/servlet/BrotliServletFilter : Unsupported major.minor version 51.0 (unable to load class org.meteogroup.jbrotli.servlet.BrotliServletFilter)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2858)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1159)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1647)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
	at org.apache.catalina.startup.WebAnnotationSet.loadClassAnnotation(WebAnnotationSet.java:145)
	at org.apache.catalina.startup.WebAnnotationSet.loadApplicationFilterAnnotations(WebAnnotationSet.java:84)
	at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:57)
	at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:297)
	at org.apache.catalina.startup.ContextConfig.start(ContextConfig.java:1078)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:261)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4612)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:601)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
	at org.apache.catalina.core.StandardService.start(StandardService.java:525)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

Thanks,

**Comment by nitram509** [comment] 2016-06-16 20:01
Seems like Microsoft's Visual C++ Redistributable for Visual Studio 2015 helped?

**Comment by nitram509** [comment] 2016-06-16 20:05
Regarding Java 6 - I don't plan to support it, because Java 6 is "End Of Life" since Feb. 2013.

Why can't you use a more modern Version?

**Comment by vmeganathan81** [comment] 2016-06-17 02:37
Hey Martin,

Yes, Microsoft's Visual C++ Redistributable for Visual Studio 2015 really helped.

Most of our production server use Java 6, and there is no road map to migrate it. If you could assist me in compiling the code in Java 6 would be great.

Thanks,

**Comment by vmeganathan81** [comment] 2016-06-17 21:47
Having some issue with js files in brotli compression, could you please take a look at screen shot and suggest if any,

![untitled](https://cloud.githubusercontent.com/assets/19844029/16165700/78090dc4-34b3-11e6-887a-1757ea5f0596.png)

**Comment by nitram509** [comment] 2016-06-19 15:11
If you want to compile with Java 1.6, I recommend the following:

* fork this project 
* modify all pom.xml files to use javac 1.6 instead of 1.7
* fix compile errors manually for the projects
   * 'jbrotli'
   * 'jbrotli-servlet'
   * e.g. ```mvn -pl jbrotli,jbrotli-servlet package```

After that, you can use the generated JAR files in your project.

**Comment by nitram509** [comment] 2016-06-19 15:19
Regarding the missing JS files ... there could be many reasons for that.
Can you please make a screenshot of the "Network" log, when the pages loads, to clarify what's going on:
* Are there any errors ?
* What's in the request-headers for e.g. "newLogin.js" ?
* What's in the response-headers for e.g. "newLogin.js" ?

**Comment by nitram509** [comment] 2016-07-19 20:33
I'm closing this issue now, as there is no feedback since one month.
Thank you for your understanding.

**Comment by danielpeintner** [comment] 2016-08-30 09:21
Hi,

I run into a similar issue getting the same UnsatisfiedLinkError
brotli.dll: Can't find dependent libraries

The jbrotli library seems to create a temp folder and puts the brotli.dll there.
This step seems to work, brotli.dll is in  ...\Local\Temp\brotli7247092319344770215\brotli.dll

It fails in the final step of tryLoadingFromTemporaryFolder() when calling Runtime.getRuntime().load(libFile.getAbsolutePath()); 

I am using Maven, Java 1.8.0_65, Windows 7

Any idea?

Thanks!


```
  boolean tryLoadingFromTemporaryFolder() throws SecurityException, IllegalStateException {

    ...

    if (loaderResult.isUsedThisClassloader() || loaderResult.isUsedSystemClassloader()) {
      loaderResult.setMadeReadable(libFile.setReadable(true));
      loaderResult.setMadeExecutable(libFile.setExecutable(true));
      Runtime.getRuntime().load(libFile.getAbsolutePath());
      return true;
    }
    return false;
  }
```

**Comment by nitram509** [comment] 2016-08-31 07:05
Hi Daniel,

thank you for your description.
Would you please add the stacktrace from the exception you get – It contains helpful information.

Regards
Martin

**Comment by danielpeintner** [comment] 2016-08-31 08:00
Hi Martin, 

Sure!
Thanks for looking into the issue.

It is currently used in a JUnit Test.

Thanks,

-- Daniel


```
java.lang.UnsatisfiedLinkError: C:\Users\bla\AppData\Local\Temp\brotli6420405013557326366\brotli.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.Runtime.load(Runtime.java:797)
        at org.meteogroup.jbrotli.libloader.LibraryLoader.tryLoadingFromTemporaryFolder(LibraryLoader.java:79)
        at org.meteogroup.jbrotli.libloader.BrotliLibraryLoader.loadBrotli(BrotliLibraryLoader.java:33)
        at com.siemens.ct.exi.css.CSStoEXITest.writeBrotli(CSStoEXITest.java:64)
        at com.siemens.ct.exi.css.CSStoEXITest._test(CSStoEXITest.java:127)
        at com.siemens.ct.exi.css.CSStoEXITest.testCapitalone(CSStoEXITest.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:255)
        at junit.framework.TestSuite.run(TestSuite.java:250)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by nitram509** [comment] 2016-08-31 22:02
Daniel,

I think the problem is something is similar like above. The error message 
"brotli.dll: Can't find dependent libraries" could also mean, that the DLL requires some Visual Studio
runtime DLL files.

Would you please install Microsoft's Visual C++ Redistributable for Visual Studio 2015
and check if it's working then? The official installer you find here:
https://www.microsoft.com/download/details.aspx?id=48145

**Comment by danielpeintner** [comment] 2016-09-01 07:57
Thanks Martin. This resolved my issue!

**Closed** 2016-09-01 19:27 UTC
